# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 13:56
from __future__ import unicode_literals

import demo.fields
import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_formentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', demo.fields.ListFiled()),
            ],
        ),
        migrations.AlterField(
            model_name='formentry',
            name='author',
            field=models.CharField(max_length=10, validators=[demo.models.validate_pre]),
        ),
    ]
